name = "MyPKG"
uuid = "ca0e221a-9d54-4550-9316-1072b3f09c31"
authors = ["Marcell <havlikmarcell@gmail.com>"]
version = "0.1.0"

[deps]
Boilerplate = "fe7df2fb-dcb5-4bf9-996b-0af1f7856ff2"
TestPKG = "face8fba-605c-446e-afeb-1a7926d8cb37"
